on:
  workflow_dispatch:
  push:

jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix build .

  check_the_coding_style:
    needs: [ check_build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run coding style checker
        run: |
          nix run github:Sigmapitech/cs \
            --extra-experimental-features 'nix-command flakes' \
            -- . --ignore-rules=C-G1
